version: "3.8"
services:
  backend:
    image: 'backend'
    container_name: backend
    build: ./backend
    environment:
      JDBC_URL: jdbc:mysql://mysql:3306/sampleDB?useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true
      JDBC_PASSWORD: test
      JDBC_USER: test
    ports:
      - "8080:8080"
    networks:
      - my-network
    depends_on:
      mysql:
        condition: service_healthy

  prod:
    container_name: prod
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    ports:
      - '80:80'
    networks:
      - my-network
  #frontend:
  #  image: 'frontend'
  #  container_name: frontend
  #  stdin_open: true
  #  depends_on:
  #    backend:
  #      condition: service_started
  #  environment:
  #    - CHOKIDAR_USEPOLLING=true
  #  build: ./frontend
  #  ports:
  #    - '3000:3000'
  #  networks:
  #    - my-network
  #  volumes:
  #    - /frontend/node_modules
  #    - .:/frontend

  # MySQL container
  mysql:
    container_name: mysql
    image: mysql:8.0.19
    networks:
      - my-network
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: sampleDB
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_ROOT_HOST: 172.*.*.*
    ports:
      - '3306:3306'
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # phpMyAdmin container
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin:5.0.2
    networks:
      - my-network
    ports:
      - "9081:80"
    environment:
      PMA_HOST: mysql
    depends_on:
      mysql:
        condition: service_healthy

# Define networks
networks:
  my-network: